# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GameSticks(object):
    def setupUi(self, GameSticks):
        GameSticks.setObjectName("GameSticks")
        GameSticks.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(GameSticks)
        self.centralwidget.setStyleSheet("background-color: rgb(214,244,172)")
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(250, 50, 363, 84))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setEnabled(True)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        GameSticks.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameSticks)
        QtCore.QMetaObject.connectSlotsByName(GameSticks)

    def retranslateUi(self, GameSticks):
        _translate = QtCore.QCoreApplication.translate
        GameSticks.setWindowTitle(_translate("GameSticks", "MainWindow"))
        self.label.setText(_translate("GameSticks", "Добро пожаловать в игру Палочки!!!"))
        self.pushButton.setText(_translate("GameSticks", "Начать игру"))
        self.pushButton_2.setText(_translate("GameSticks", "Выйти из игры"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GameSticks = QtWidgets.QMainWindow()
    ui = Ui_GameSticks()
    ui.setupUi(GameSticks)
    GameSticks.show()
    sys.exit(app.exec_())
